#pragma once

// 0: ESP32-P4-Function-EV-Board by Espressif
// 1: Pico Held 2 v 1.2  // prototype
// 2: Pico Held 2 v 1.3  // prototype
// 3: Pico Held 2 v 1.4  // Released version

#define HW_CONFIG (3)

#if HW_CONFIG==0
// ADC calibration coefficients
#define PWR_BAT_ADC_A (0)
#define PWR_BAT_ADC_B (0)
#define PWR_EXT_ADC_A (0)
#define PWR_EXT_ADC_B (0)

// Physical battery and power supply parameters (in mV)
#define PWR_BAT_MAX_VOL (4050)
#define PWR_BAT_MIN_VOL (3400)
#define PWR_CHG_MIN_VOL (4170)

#define PIN_PWR_EN (GPIO_NUM_NC)
#define PIN_CHG_STAT (GPIO_NUM_NC)
#define PIN_SND_EN (GPIO_NUM_NC)

// ESP function board
#define DISPLAY_DRIVER "lcd_ek79007.h"
//#define DISPLAY_DRIVER "lcd_p055h020v2.h"  // not working: no 2 lane support?
//#define DISPLAY_DRIVER "lcd_kd040hdfid032.h"
//#define DISPLAY_DRIVER "lcd_dxq3d9502.h"
//#define DISPLAY_DRIVER "lcd_txw350099c0.h"  // not working: init seq wrong?
//#define DISPLAY_DRIVER "lcd_hd395003c30.h"

#define DEVBOARD

#define PIN_SD_DAT0_MISO (GPIO_NUM_39)
#define PIN_SD_DAT1 (GPIO_NUM_40)
#define PIN_SD_DAT2 (GPIO_NUM_41)
#define PIN_SD_DAT3_CS (GPIO_NUM_42)
#define PIN_SD_SCK (GPIO_NUM_43)
#define PIN_SD_CMD_MOSI (GPIO_NUM_44)

#define PIN_ANA_VBAT (GPIO_NUM_NC)
#define PIN_ANA_VEXT (GPIO_NUM_NC)

#define PIN_LCD_RST (GPIO_NUM_27)
#define PIN_LCD_BL_PWM (GPIO_NUM_26)

#define PIN_BTN_A (GPIO_NUM_NC)
#define PIN_BTN_B (GPIO_NUM_NC)
#define PIN_BTN_X (GPIO_NUM_NC)
#define PIN_BTN_Y (GPIO_NUM_NC)
#define PIN_BTN_LEFT (GPIO_NUM_NC)
#define PIN_BTN_RGHT (GPIO_NUM_NC)

#define PIN_BTN_UP (GPIO_NUM_NC)
#define PIN_BTN_DOWN (GPIO_NUM_NC)
#define PIN_BTN_ST (GPIO_NUM_NC)
#define PIN_BTN_SEL (GPIO_NUM_NC)
#define PIN_BTN_L (GPIO_NUM_NC)
#define PIN_BTN_R (GPIO_NUM_NC)
#define PIN_BTN_SW (GPIO_NUM_NC)

#define PIN_ANA_X (GPIO_NUM_NC)
#define PIN_ANA_Y (GPIO_NUM_NC)

#define BUTTON_MAP {\
  { BUTTON_A,     GPIO_NUM_NC,     0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL, 0, 0 }, \
  { BUTTON_B,     GPIO_NUM_NC,     0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL, 0, 0 }, \
  { BUTTON_X,     GPIO_NUM_NC,     0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL, 0, 0 }, \
  { BUTTON_Y,     GPIO_NUM_NC,     0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL, 0, 0 }, \
  { BUTTON_LEFT,  GPIO_NUM_NC,     0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL, 0, 0 }, \
  { BUTTON_RIGHT, GPIO_NUM_NC,     0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL, 0, 0 }, \
  { BUTTON_UP,    GPIO_NUM_NC,     0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL, 0, 0 }, \
  { BUTTON_DOWN,  GPIO_NUM_NC,     0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL, 0, 0 }, \
  { BUTTON_ST,    GPIO_NUM_NC,     0, GPIO_PULLDOWN_ONLY, BUTTON_PRESSED_WHEN_HI, BUTTON_DIGITAL, 0, 0 }, \
  { BUTTON_SEL,   GPIO_NUM_NC,     0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL, 0, 0 }, \
  { BUTTON_L,     GPIO_NUM_NC,     0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL, 0, 0 }, \
  { BUTTON_R,     GPIO_NUM_NC,     0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL, 0, 0 }, \
  { BUTTON_SW,    GPIO_NUM_NC,     0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL, 0, 0 }, \
};

#elif HW_CONFIG==1
// Pico Held rev. 1.2
#define DISPLAY_DRIVER "lcd_dxq3d9502.h"
#define LCD_ROTATION

// ADC calibration coefficients
#define PWR_BAT_ADC_A (1365)
#define PWR_BAT_ADC_B (-597)
#define PWR_EXT_ADC_A (1)
#define PWR_EXT_ADC_B (0)

// Physical battery and power supply parameters (in mV)
#define PWR_BAT_MAX_VOL (4050)
#define PWR_BAT_MIN_VOL (3400)
#define PWR_CHG_MIN_VOL (4170)

#define PIN_PWR_EN (GPIO_NUM_53)
#define PIN_CHG_STAT (GPIO_NUM_52)

#define PIN_LCD_BL_EN (GPIO_NUM_7)
#define PIN_LCD_BL_PWM (GPIO_NUM_22)
#define PIN_LCD_RST (GPIO_NUM_23)

#define PIN_SND_EN (GPIO_NUM_30)
#define PIN_I2S_BCK (28)
#define PIN_I2S_WS (29)
#define PIN_I2S_DOUT (25)

#define PIN_SD_DAT0_MISO (GPIO_NUM_39)
#define PIN_SD_DAT1 (GPIO_NUM_40)
#define PIN_SD_DAT2 (GPIO_NUM_41)
#define PIN_SD_DAT3_CS (GPIO_NUM_42)
#define PIN_SD_SCK (GPIO_NUM_43)
#define PIN_SD_CMD_MOSI (GPIO_NUM_44)
#define PIN_SD_DET (GPIO_NUM_47)

#define PIN_BTN_A (GPIO_NUM_31)
#define PIN_BTN_B (GPIO_NUM_5)
#define PIN_BTN_X (GPIO_NUM_32)
#define PIN_BTN_Y (GPIO_NUM_54)
#define PIN_BTN_LEFT (GPIO_NUM_14)
#define PIN_BTN_RGHT (GPIO_NUM_12)

#define PIN_BTN_UP (GPIO_NUM_13)
#define PIN_BTN_DOWN (GPIO_NUM_15)
#define PIN_BTN_ST (GPIO_NUM_45)
#define PIN_BTN_SEL (GPIO_NUM_35)
#define PIN_BTN_L (GPIO_NUM_11)
#define PIN_BTN_R (GPIO_NUM_4)
#define PIN_BTN_SW (GPIO_NUM_1)

#define PIN_ANA_X (GPIO_NUM_16)
#define PIN_ANA_Y (GPIO_NUM_17)

#define PIN_ANA_VBAT (GPIO_NUM_19)
#define PIN_ANA_VEXT (GPIO_NUM_18)

#define PIN_STAT_LED (GPIO_NUM_33)

#define BUTTON_MAP {\
  { BUTTON_A,     PIN_BTN_A,     0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL, 0, 0 }, \
  { BUTTON_B,     PIN_BTN_B,     0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL, 0, 0 }, \
  { BUTTON_X,     PIN_BTN_X,     0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL, 0, 0 }, \
  { BUTTON_Y,     PIN_BTN_Y,     0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL, 0, 0 }, \
  { BUTTON_LEFT,  PIN_BTN_LEFT,  0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL, 0, 0 }, \
  { BUTTON_RIGHT, PIN_BTN_RGHT,  0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL, 0, 0 }, \
  { BUTTON_UP,    PIN_BTN_UP,    0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL, 0, 0 }, \
  { BUTTON_DOWN,  PIN_BTN_DOWN,  0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL, 0, 0 }, \
  { BUTTON_ST,    PIN_BTN_ST,    0, GPIO_PULLDOWN_ONLY, BUTTON_PRESSED_WHEN_HI, BUTTON_DIGITAL, 0, 0 }, \
  { BUTTON_SEL,   PIN_BTN_SEL,   0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL, 0, 0 }, \
  { BUTTON_L,     PIN_BTN_L,     0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL, 0, 0 }, \
  { BUTTON_R,     PIN_BTN_R,     0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL, 0, 0 }, \
  { BUTTON_SW,    PIN_BTN_SW,    0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL, 0, 0 }, \
}; \

#elif HW_CONFIG==2
// Pico Held rev. 1.3
#define DISPLAY_DRIVER "lcd_hd395003c30.h"
#define LCD_ROTATION

// ADC calibration coefficients
#define PWR_BAT_ADC_A (1365)
#define PWR_BAT_ADC_B (-597)
#define PWR_EXT_ADC_A (2749)
#define PWR_EXT_ADC_B (-948)

// Physical battery and power supply parameters (in mV)
#define PWR_BAT_MAX_VOL (4050)
#define PWR_BAT_MIN_VOL (3400)
#define PWR_CHG_MIN_VOL (4170)

#define PIN_PWR_EN (GPIO_NUM_52)
#define PIN_CHG_STAT (GPIO_NUM_53)

#define PIN_LCD_BL_EN (GPIO_NUM_7)
#define PIN_LCD_BL_PWM (GPIO_NUM_22)
#define PIN_LCD_RST (GPIO_NUM_23)

#define PIN_SND_EN (GPIO_NUM_30)
#define PIN_I2S_BCK (28)
#define PIN_I2S_WS (29)
#define PIN_I2S_DOUT (25)

#define PIN_SD_DAT0_MISO (GPIO_NUM_39)
#define PIN_SD_DAT1 (GPIO_NUM_40)
#define PIN_SD_DAT2 (GPIO_NUM_41)
#define PIN_SD_DAT3_CS (GPIO_NUM_42)
#define PIN_SD_SCK (GPIO_NUM_43)
#define PIN_SD_CMD_MOSI (GPIO_NUM_44)
#define PIN_SD_DET (GPIO_NUM_47)

#define PIN_BTN_A (GPIO_NUM_31)
#define PIN_BTN_B (GPIO_NUM_5)
#define PIN_BTN_X (GPIO_NUM_32)
#define PIN_BTN_Y (GPIO_NUM_54)
#define PIN_BTN_LEFT (GPIO_NUM_14)
#define PIN_BTN_RGHT (GPIO_NUM_12)

#define PIN_BTN_UP (GPIO_NUM_13)
#define PIN_BTN_DOWN (GPIO_NUM_15)
#define PIN_BTN_ST (GPIO_NUM_45)
#define PIN_BTN_SEL (GPIO_NUM_35)
#define PIN_BTN_L (GPIO_NUM_11)
#define PIN_BTN_R (GPIO_NUM_4)
#define PIN_BTN_SW (GPIO_NUM_1)

#define PIN_ANA_X (GPIO_NUM_16)
#define PIN_ANA_Y (GPIO_NUM_17)

#define PIN_ANA_VBAT (GPIO_NUM_18)
#define PIN_ANA_VEXT (GPIO_NUM_19)

#define BUTTON_MAP {\
  { BUTTON_A,     PIN_BTN_A,     0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL, 0, 0 }, \
  { BUTTON_B,     PIN_BTN_B,     0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL, 0, 0 }, \
  { BUTTON_X,     PIN_BTN_X,     0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL, 0, 0 }, \
  { BUTTON_Y,     PIN_BTN_Y,     0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL, 0, 0 }, \
  { BUTTON_LEFT,  PIN_BTN_LEFT,  0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL, 0, 0 }, \
  { BUTTON_RIGHT, PIN_BTN_RGHT,  0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL, 0, 0 }, \
  { BUTTON_UP,    PIN_BTN_UP,    0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL, 0, 0 }, \
  { BUTTON_DOWN,  PIN_BTN_DOWN,  0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL, 0, 0 }, \
  { BUTTON_ST,    PIN_BTN_ST,    0, GPIO_PULLDOWN_ONLY, BUTTON_PRESSED_WHEN_HI, BUTTON_DIGITAL, 0, 0 }, \
  { BUTTON_SEL,   PIN_BTN_SEL,   0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL, 0, 0 }, \
  { BUTTON_L,     PIN_BTN_L,     0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL, 0, 0 }, \
  { BUTTON_R,     PIN_BTN_R,     0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL, 0, 0 }, \
  { BUTTON_SW,    PIN_BTN_SW,    0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL, 0, 0 }, \
};
#elif HW_CONFIG==3
// Pico Held rev. 1.4
#define DISPLAY_DRIVER "lcd_hd395003c30.h"
#define LCD_ROTATION

// ADC calibration coefficients
#define PWR_BAT_ADC_A (5803)
#define PWR_BAT_ADC_B (-11511)
#define PWR_EXT_ADC_A (2749)
#define PWR_EXT_ADC_B (-948)

// Physical battery and power supply parameters (in mV)
#define PWR_BAT_MAX_VOL (4050)
#define PWR_BAT_MIN_VOL (3400)
#define PWR_CHG_MIN_VOL (4170)

#define PIN_PWR_EN (GPIO_NUM_52)
#define PIN_CHG_STAT (GPIO_NUM_53)

#define PIN_LCD_BL_EN (GPIO_NUM_7)
#define PIN_LCD_BL_PWM (GPIO_NUM_22)
#define PIN_LCD_RST (GPIO_NUM_23)

#define PIN_SND_EN (GPIO_NUM_30)
#define PIN_I2S_BCK (28)
#define PIN_I2S_WS (29)
#define PIN_I2S_DOUT (25)

#define PIN_SD_DAT0_MISO (GPIO_NUM_39)
#define PIN_SD_DAT1 (GPIO_NUM_40)
#define PIN_SD_DAT2 (GPIO_NUM_41)
#define PIN_SD_DAT3_CS (GPIO_NUM_42)
#define PIN_SD_SCK (GPIO_NUM_43)
#define PIN_SD_CMD_MOSI (GPIO_NUM_44)
#define PIN_SD_DET (GPIO_NUM_47)

#define PIN_BTN_A (GPIO_NUM_31)
#define PIN_BTN_B (GPIO_NUM_5)
#define PIN_BTN_X (GPIO_NUM_32)
#define PIN_BTN_Y (GPIO_NUM_54)
#define PIN_BTN_LEFT (GPIO_NUM_14)
#define PIN_BTN_RGHT (GPIO_NUM_12)

#define PIN_BTN_UP (GPIO_NUM_13)
#define PIN_BTN_DOWN (GPIO_NUM_15)
#define PIN_BTN_ST (GPIO_NUM_49)
#define PIN_BTN_SEL (GPIO_NUM_35)
#define PIN_BTN_L (GPIO_NUM_11)
#define PIN_BTN_R (GPIO_NUM_4)
#define PIN_BTN_SW (GPIO_NUM_1)

#define PIN_ANA_X (GPIO_NUM_16)
#define PIN_ANA_Y (GPIO_NUM_17)

#define PIN_ANA_VBAT (GPIO_NUM_18)
#define PIN_ANA_VEXT (GPIO_NUM_19)

#define BUTTON_MAP {\
  { BUTTON_A,     PIN_BTN_A,     0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL,    0, 0 }, \
  { BUTTON_B,     PIN_BTN_B,     0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL,    0, 0 }, \
  { BUTTON_X,     PIN_BTN_X,     0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL,    0, 0 }, \
  { BUTTON_Y,     PIN_BTN_Y,     0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL,    0, 0 }, \
  { BUTTON_LEFT,  PIN_BTN_LEFT,  0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL,    0, 0 }, \
  { BUTTON_RIGHT, PIN_BTN_RGHT,  0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL,    0, 0 }, \
  { BUTTON_UP,    PIN_BTN_UP,    0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL,    0, 0 }, \
  { BUTTON_DOWN,  PIN_BTN_DOWN,  0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL,    0, 0 }, \
  { BUTTON_ST,    PIN_BTN_ST,    0, GPIO_PULLDOWN_ONLY, BUTTON_PRESSED_WHEN_HI, BUTTON_ANALOG,  3500, 0 }, \
  { BUTTON_SEL,   PIN_BTN_SEL,   0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL,    0, 0 }, \
  { BUTTON_L,     PIN_BTN_L,     0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL,    0, 0 }, \
  { BUTTON_R,     PIN_BTN_R,     0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL,    0, 0 }, \
  { BUTTON_SW,    PIN_BTN_SW,    0, GPIO_PULLUP_ONLY,   BUTTON_PRESSED_WHEN_LO, BUTTON_DIGITAL,    0, 0 }, \
}; 
#endif


